Variant 1
ViktoriaV-start/karty-podskazhut pull request #1
Opened 2024-12-04 07:06 UTC by ViktoriaV-start

2024-12-11 20:10 UTC, Avaakum requested changes
Развернуть общий комментарий ⬇︎

Доброго времени суток. У вас получилась хорошая работа!

_Что понравилось:_

- работают темы
- отличная структура файлов проекта
- Хорошая семантика
- Хорошие стили 
- Отзывчивая верстка
- Похоже на макет на брейк-поинтах


_Что необходимо исправить:_


- **Все комментарии, кроме комментариев с пометками «Можно лучше» и «Отлично». А так же не забудьте проверить, есть ли свёрнутые комментарии, которые обычно находятся по центру страницы с ревью при прокрутке вниз, и выглядят следующим образом https://disk.yandex.ru/i/FyX-8tzeqLjimw**

- https://disk.yandex.ru/i/Nawm8rOiW-G4eQ полоса при ховере у ссылок не видна при тёмной теме


- https://disk.yandex.ru/i/B4cfnQ9bedRdkQ  Маркеры списка должны находится по центру  напротив элемента списка, а не по верхней строке. Для этого нужно опустить вниз буллит на  50% элемента списка , например с помощью  inset-block-start и затем поднять его на половину собственной высоты(7.5px) с помощью margin-block-start. 








_Что можно улучшить:_

- Все комментарии с пометкой "Можно лучше"
- Для всех функций ` var() ` в CSS нужно задать резервные значения,  на случай если доступ к кастомному свойству по имени будет невозможен. 
- Можно использовать атрибуты `target="_blank"` для ссылок на сторонние ресурсы для того чтобы пользователю не приходилось заново открывать сайт проекта
- больше использовать currentColor, где это возможно
- больше использовать vi вместо vw


Желаю успеха!

2024-12-11 20:10 UTC, Avaakum commented on index.html
> +        фанаты Ино. Есть довольно симпатичные веб-сайты с
Слово "веб-сайты" так же должно быть ссылкой из макета

2024-12-11 20:10 UTC, Avaakum commented on index.html
> +          target="_blank">iOS</a>
Между тегов ссылки должно быть "для iOS"

2024-12-11 20:10 UTC, Avaakum commented on styles/style.css
> +  width: 219px;
Вместо фиксированной ширины используйте значение ` calc(100% + 8px); `

2024-12-11 20:10 UTC, Avaakum commented on index.html
> +    <div class="header__logo">
---

**Можно лучше:**

Логотип должен быть ссылкой **без атрибута href,**(что бы по ссылке не было перехода). А так же, что бы при навигации с клавиатуры этот элемент не получал видимый фокус. **Пустой атрибут href тоже нужно удалить.**

2024-12-11 20:10 UTC, Avaakum commented on index.html
> +        <source srcset="./images/cards-2x.png 2x, ./images/cards-1x.png 1x" type="image/png">
Вместо этого тега <source> задайте атрибут srcset с этим значением сразу для тега  img вместо атрибута src

Тут так же стоит использовать srcset и указать 2 изображения в значении атрибута. Вместо последнего source и img, тогда будет только img c srcset  вместо src. На ошибку валидатора в данном случае можно не обращать внимание

2024-12-11 20:10 UTC, Avaakum commented on index.html
> +          alt="На столе вместе с телефоном, ручкой и блокнотом лежат коробка с карточками и открытая каточка с надписью 'Trus in the you of now'">
---

**Отлично:**

Хороший альт

2024-12-11 20:10 UTC, Avaakum commented on index.html
> +    <figure class="content__figure">
---

**Отлично:**

Отличная семантика и структура

2024-12-11 20:10 UTC, Avaakum commented on index.html
> +      <blockquote class="content__blockquote">
---

**Отлично:**

Отличная семантика

2024-12-11 20:10 UTC, Avaakum commented on styles/style.css
> +.page {
**Нужно исправить:** Дублирование селектора (или, если страница с адаптацией, то дублирование селектора внутри одного диапазона ширин).

---

Этого не следует допускать в проекте, т. к. данный подход увеличивает вес правил, написанных в селекторе ниже по коду, правила, написанные в селекторе выше, могут перебиваться правилами, описанными в селекторе ниже. Такой подход усложняет разработку и поддержку кода.
Пожалуйста, проконтролируйте по всему файлу, чтобы обращение к селектору использовалось в проекте единожды. Для удобства навигации можно использовать поиск по строке.
*/

2024-12-12 18:26 UTC, ViktoriaV-start commented on index.html
> +        <source srcset="./images/cards-2x.png 2x, ./images/cards-1x.png 1x" type="image/png">
Не очень поняла, я специально уточняла в пачке, как прописывать изображения для разные вариантов формата, разрешения экрана и размеров экрана  и это как раз такой вариант с picture.
Если с img - то не вижу в доках, как прописать разные форматыЮ
Вот такой вариант, но не прописан type - подходит?:
<img
    src="./images/cards-1x.png"
    srcset="
    ./images/cards-2x.webp 2x,
    ./images/cards-1x.webp 1x,
    ./images/cards-2x.png 2x,
    ./images/cards-1x.png 1x"
    alt="На столе вместе с телефоном, ручкой и блокнотом лежат коробка с карточками и открытая карточка с надписью 'Trust in the you of now'">

2024-12-13 18:26 UTC, Avaakum requested changes
Развернуть общий комментарий ⬇︎

Здравствуйте! Работа принимается.  Желаю вам удачи в следующих спринтах и проектах! 

---

_Что необходимо исправить:_

- **Все комментарии в коде. А так же не забудьте проверить, есть ли свёрнутые комментарии, которые обычно находятся по центру страницы с ревью при прокрутке вниз, и выглядят следующим образом https://disk.yandex.ru/i/FyX-8tzeqLjimw**

-  при тёмной теме ховер у ссылок не виден



---




Ссылки:

- Можно использовать неразрывные пробелы для того чтобы текст не переносился в неожиданных местах. Неразрывные пробелы заменяют обычные, если нужно чтобы какая-то фраза не переносилась, например не нужно чтобы "на собаках" раскидывалось по разным строчкам при некоторых ширинах экранов, тогда `«на&nbsp;собаках»`. Но если страница с адаптацией, то всегда стоит проверять как текст с пробелами выглядит на всех ширинах.
- Про альтернативный текст для картинок https://habr.com/ru/post/341810/
- [Ссылка про подгрузку шрифтов](https://only-to-top.ru/blog/tools/2019-03-13-nastrojte-pokaz-vsego-teksta-vo-vremya-zagruzki-veb-shriftov.html) 


Несколько  ссылок на материал по теме нативных CSS переменных от авторов практикума:

- [1 часть](https://tproger.ru/articles/custom-properties-in-css-part-1/)

- [2 часть](https://tproger.ru/articles/custom-properties-in-css-part-2/)

- [3 часть](https://tproger.ru/articles/custom-properties-in-css-part-3/)



**Hover и псевдоэлементы**

Псевдоэлементы:

- https://developer.mozilla.org/ru/docs/Web/CSS/Pseudo-elements
- https://habr.com/ru/post/154319/
-  https://webformyself.com/krutoe-ispolzovanie-psevdoelementov-css-before-i-after/
-  https://www.internet-technologies.ru/articles/5-priemov-css3-s-psevdoelementami-before-i-after.html

Hover:

- Базовая спека http://htmlbook.ru/css/hover		
- https://codepen.io/igosheva_nastya/pen/qeJmMM



**Игры по flex/grid**

- https://flexboxfroggy.com/#ru
- https://cssgridgarden.com/#ru




**Grid-layout**

- https://css-tricks.com/snippets/css/complete-guide-grid/ (en)
- https://tuhub.ru/posts/css-grid-complete-guide
- https://medium.com/@stasonmars/вёрстка-на-grid-в-css-полное-руководство-и-справочник-220508316f8b

2024-12-13 18:26 UTC, Avaakum commented on index.html
> +        <source srcset="./images/cards-2x.png 2x, ./images/cards-1x.png 1x" type="image/png">
Тут имелось в виду убрать только тег source с картинками в формате png. Остальные теги source нужно оставить. И вместо этого тега добавить атрибут srcset с картинками png разной плотности пикселей для тега img.

2024-12-14 19:52 UTC, merged